version: '2'

services:
  mysql:
    build: ./mysql
    volumes:
        - /vol/mysql:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=test
        - MYSQL_USER=app
        - MYSQL_PASSWORD=app
    expose:
        - 3306
    ports:
        - "3306:3306"
